# Change these first
owner: COSGrid # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: COSGrid
    url: https://cosgrid.com
  - name: Google
    url: https://www.google.com
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: uptime.cosgrid.com
  baseUrl: /upptime
  logoUrl: https://media.licdn.com/dms/image/C510BAQHqNdK6VsHGvA/company-logo_200_200/0/1571128615896?e=1688601600&v=beta&t=1yzeRaAA_VfRXUuMjMMlkyUVOF6f-dfMWM9ntDf_djc
  name: COSGrid
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/COSGrid/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
