name: Get token
description: Retrieve a GitHub token to used, based on the user-configured method.

outputs:
  token:
    description: The GitHub token
    value: ${{ steps.token.outputs.token || secrets.GH_PAT || github.token }}

runs:
  using: "composite"
  steps:
    - name: Get Token
      if: ${{ vars.GH_APP_ID && secrets.GH_APP_PRIVATE_KEY }}
      uses: actions/create-github-app-token@v3
      id: token
      with:
        client-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}